In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

# Load dataset

In [2]:
vgsales_2016 = pd.read_csv('dataset\Video Games Sales Dataset\Video_Games_Sales_as_at_22_Dec_2016.csv')
vgsales_2016

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
vgsales_PS4 = pd.read_csv('dataset\Video Games Sales Dataset\PS4_GamesSales.csv')
vgsales_PS4

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80
...,...,...,...,...,...,...,...,...,...
1029,Fallen Legion: Flames of Rebellion,NaN,Role-Playing,NaN,0.00,0.00,0.00,0.00,0.00
1030,Radial G Racing Revolved,2017.0,Racing,Tammeka Games,0.00,0.00,0.00,0.00,0.00
1031,The Mummy Demastered,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00
1032,Project Nimbus: Code Mirai,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00
1033,Battle Chef Brigade,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00

In [4]:
vgsales_XOne = pd.read_csv('dataset\Video Games Sales Dataset\XboxOne_GameSales.csv')
vgsales_XOne

,Pos,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,1,Grand Theft Auto V,2014.0,Action,Rockstar Games,4.70,3.25,0.01,0.76,8.72
1,2,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,4.63,2.04,0.02,0.68,7.37
2,3,Call of Duty: WWII,2017.0,Shooter,Activision,3.75,1.91,0.00,0.57,6.23
3,4,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,3.76,1.47,0.00,0.54,5.77
4,5,MineCraft,2014.0,Misc,Microsoft Studios,3.23,1.71,0.00,0.49,5.43
...,...,...,...,...,...,...,...,...,...,...
608,609,Biomutant,2018.0,Action,THQ Nordic,0.00,0.00,0.00,0.00,0.00
609,610,Biomutant,2019.0,Action,THQ Nordic,0.00,0.00,0.00,0.00,0.00
610,611,de Blob,2017.0,Platform,THQ Nordic,0.00,0.00,0.00,0.00,0.00
611,612,Outcast: Second Contact,2017.0,Adventure,Bigben Interactive,0.00,0.00,0.00,0.00,0.00
612,613,Code Vein,2019.0,Action,Bandai Namco Entertainment,0.00,0.00,0.00,0.00,0.00

# Data Cleaning

## Select Columns

Take only selected columns for analysis such as **game name**, **game platform**, **release year**, **genre**, **publisher**, sales in **NA**, **EU**, **JP**, **Other**, and **global**.

*Note: Sales is in million number of copies*.

In [5]:
# select columns in 'vgsales_2016'
vgsales_2016 = vgsales_2016[['Name', 'Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales', 
                            'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']]
vgsales_2016

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01

In [6]:
# create 'Platform' column
vgsales_PS4['Platform'] = 'PS4'

# rename the columns
vgsales_PS4.columns = ['Name', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales', 
                       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales', 'Platform']

# rearrange the columns order
vgsales_PS4 = vgsales_PS4[['Name', 'Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales', 
                            'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']]
vgsales_PS4

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Grand Theft Auto V,PS4,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,PS4,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,PS4,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,PS4,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,PS4,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80
...,...,...,...,...,...,...,...,...,...,...
1029,Fallen Legion: Flames of Rebellion,PS4,NaN,Role-Playing,NaN,0.00,0.00,0.00,0.00,0.00
1030,Radial G Racing Revolved,PS4,2017.0,Racing,Tammeka Games,0.00,0.00,0.00,0.00,0.00
1031,The Mummy Demastered,PS4,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00
1032,Project Nimbus: Code Mirai,PS4,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00
1033,Battle Chef Brigade,PS4,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00

In [7]:
# create 'Platform' column
vgsales_XOne['Platform'] = 'XOne'

# drop 'Pos' column
vgsales_XOne.drop('Pos', axis = 1, inplace = True)

# rename the columns
vgsales_XOne.columns = ['Name', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales', 
                       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales', 'Platform']

# rearrange the columns order
vgsales_XOne = vgsales_XOne[['Name', 'Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales', 
                            'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']]
vgsales_XOne

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Grand Theft Auto V,XOne,2014.0,Action,Rockstar Games,4.70,3.25,0.01,0.76,8.72
1,Call of Duty: Black Ops 3,XOne,2015.0,Shooter,Activision,4.63,2.04,0.02,0.68,7.37
2,Call of Duty: WWII,XOne,2017.0,Shooter,Activision,3.75,1.91,0.00,0.57,6.23
3,Red Dead Redemption 2,XOne,2018.0,Action-Adventure,Rockstar Games,3.76,1.47,0.00,0.54,5.77
4,MineCraft,XOne,2014.0,Misc,Microsoft Studios,3.23,1.71,0.00,0.49,5.43
...,...,...,...,...,...,...,...,...,...,...
608,Biomutant,XOne,2018.0,Action,THQ Nordic,0.00,0.00,0.00,0.00,0.00
609,Biomutant,XOne,2019.0,Action,THQ Nordic,0.00,0.00,0.00,0.00,0.00
610,de Blob,XOne,2017.0,Platform,THQ Nordic,0.00,0.00,0.00,0.00,0.00
611,Outcast: Second Contact,XOne,2017.0,Adventure,Bigben Interactive,0.00,0.00,0.00,0.00,0.00
612,Code Vein,XOne,2019.0,Action,Bandai Namco Entertainment,0.00,0.00,0.00,0.00,0.00

## Remove missing value

remove any missing values since we can't impute or predict it appropriately.

In [8]:
# check missing values in 'vgsales_2016'
print('missing value in "vgsales_2016"')
print(vgsales_2016.isnull().sum())

missing value in "vgsales_2016"
Name                 2
Platform             0
Year_of_Release    269
Genre                2
Publisher           54
NA_Sales             0
EU_Sales             0
JP_Sales             0
Other_Sales          0
Global_Sales         0
dtype: int64

In [9]:
# check missing values in 'vgsales_PS4'
print('missing value in "vgsales_PS4"')
print(vgsales_PS4.isnull().sum())

missing value in "vgsales_PS4"
Name                 0
Platform             0
Year_of_Release    209
Genre                0
Publisher          209
NA_Sales             0
EU_Sales             0
JP_Sales             0
Other_Sales          0
Global_Sales         0
dtype: int64

In [10]:
# check missing values in 'vgsales_XOne'
print('missing value in "vgsales_XOne"')
print(vgsales_XOne.isnull().sum())

missing value in "vgsales_XOne"
Name                 0
Platform             0
Year_of_Release    108
Genre                0
Publisher          108
NA_Sales             0
EU_Sales             0
JP_Sales             0
Other_Sales          0
Global_Sales         0
dtype: int64

In [11]:
# remove any missing values in dataset
vgsales_2016 = vgsales_2016.dropna()
vgsales_PS4 = vgsales_PS4.dropna()
vgsales_XOne = vgsales_XOne.dropna()

# cross-check missing values
print(vgsales_2016.isnull().sum().sum())
print(vgsales_PS4.isnull().sum().sum())
print(vgsales_XOne.isnull().sum().sum())

0
0
0

## Change data types

`Year_of_Release` should be `object` data types

In [12]:
# change data types in Year_of_Release column
vgsales_2016['Year_of_Release'] = vgsales_2016['Year_of_Release'].astype('int64').astype('object')
vgsales_PS4['Year_of_Release'] = vgsales_PS4['Year_of_Release'].astype('int64').astype('object')
vgsales_XOne['Year_of_Release'] = vgsales_XOne['Year_of_Release'].astype('int64').astype('object')

## Concatenate the dataset

Concatenate `vgsales_2016`, `vgsales_PS4`, and `vgsales_XOne`.

In [13]:
# concatenate the dataset
vgsales = pd.concat([vgsales_2016, vgsales_PS4, vgsales_XOne], axis = 0).reset_index(drop = True)

## Remove duplicate observations

In [14]:
# check duplicate observations in first 10 rows
vgsales[vgsales.duplicated(subset = ['Name','Platform'], keep = False)].sort_values(by = ['Name', 'Platform']).head(10)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
9032,7 Days to Die,PS4,2016,Action,Telltale Games,0.04,0.08,0.0,0.02,0.14
16750,7 Days to Die,PS4,2016,Action,Telltale Games,0.09,0.08,0.0,0.03,0.21
12638,7 Days to Die,XOne,2016,Action,Telltale Games,0.03,0.02,0.0,0.00,0.05
17496,7 Days to Die,XOne,2016,Action,Telltale Games,0.09,0.02,0.0,0.01,0.12
10701,Adventure Time: Finn & Jake Investigations,PS4,2015,Action,Little Orbit,0.03,0.05,0.0,0.02,0.09
16801,Adventure Time: Finn & Jake Investigations,PS4,2015,Action,Little Orbit,0.07,0.05,0.0,0.02,0.14
12693,Adventure Time: Finn & Jake Investigations,XOne,2015,Action,Little Orbit,0.03,0.02,0.0,0.00,0.05
17544,Adventure Time: Finn & Jake Investigations,XOne,2015,Action,Little Orbit,0.04,0.02,0.0,0.01,0.06
14643,Aegis of Earth: Protonovus Assault,PS4,2016,Action,PQube,0.02,0.00,0.0,0.00,0.03
17002,Aegis of Earth: Protonovus Assault,PS4,2016,Action,PQube,0.03,0.01,0.0,0.01,0.04

In [15]:
# check duplicate observations in last 10 rows
vgsales[vgsales.duplicated(subset = ['Name','Platform'], keep = False)].sort_values(by = ['Name', 'Platform']).tail(10)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
7407,Zombie Army Trilogy,PS4,2015,Shooter,Rebellion Developments,0.05,0.12,0.00,0.03,0.20
16743,Zombie Army Trilogy,PS4,2015,Shooter,Rebellion Developments,0.06,0.13,0.00,0.03,0.22
10133,Zombie Army Trilogy,XOne,2015,Shooter,Rebellion Developments,0.05,0.05,0.00,0.01,0.11
17497,Zombie Army Trilogy,XOne,2015,Shooter,Rebellion Developments,0.05,0.05,0.00,0.01,0.12
5110,Zoo Tycoon (2013),XOne,2013,Simulation,Microsoft Game Studios,0.18,0.15,0.00,0.03,0.36
17370,Zoo Tycoon (2013),XOne,2013,Simulation,Microsoft Studios,0.25,0.18,0.00,0.04,0.48
6761,Zumba Fitness: World Party,XOne,2013,Misc,Majesco Entertainment,0.17,0.05,0.00,0.02,0.24
17423,Zumba Fitness: World Party,XOne,2013,Misc,Majesco Entertainment,0.17,0.05,0.00,0.02,0.24
525,inFAMOUS: Second Son,PS4,2014,Action,Sony Computer Entertainment,1.28,0.98,0.07,0.46,2.79
16472,inFAMOUS: Second Son,PS4,2014,Action-Adventure,Sony Computer Entertainment,1.35,1.09,0.07,0.50,3.01

In [16]:
# number of duplicate games
print('total duplicates:', vgsales[vgsales.duplicated(subset = ['Name','Platform'], keep = False)].sort_values(by = ['Name', 'Platform']).shape[0]//2)

total duplicates: 607

In [17]:
# drop duplicates
vgsales = vgsales.drop_duplicates(subset = ['Name','Platform'], keep = 'first')
vgsales = vgsales.reset_index(drop = True)

## Sanity check the columns

In [18]:
# describe the object data type column
display(vgsales.describe(include = 'object'))

# describe the non-object data type column
display(vgsales.describe(exclude = 'object'))

,Name,Platform,Year_of_Release,Genre,Publisher
count,17139,17139,17139,17139,17139
unique,11824,31,41,17,645
top,Need for Speed: Most Wanted,PS2,2008,Action,Electronic Arts
freq,10,2127,1427,3485,1360

           NA_Sales      EU_Sales      JP_Sales   Other_Sales  Global_Sales
count  17139.000000  17139.000000  17139.000000  17139.000000  17139.000000
mean       0.260491      0.146731      0.076253      0.048108      0.531834
std        0.808688      0.511766      0.305828      0.188495      1.549829
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.060000
50%        0.070000      0.020000      0.000000      0.010000      0.160000
75%        0.230000      0.110000      0.030000      0.030000      0.460000
max       41.360000     28.960000     10.220000     10.570000     82.530000

In [19]:
# check unique values in 'Platform', 'Year_of_Release', 'Genre', 'Publisher'
for col in [column for column in vgsales.columns if column in ['Platform', 'Year_of_Release', 'Genre', 'Publisher']]:
    temp = vgsales[col].unique()
    temp.sort()
    print('unique values in "{}":\n{}'.format(col, temp))
    print()

unique values in "Platform":
['2600' '3DO' '3DS' 'DC' 'DS' 'GB' 'GBA' 'GC' 'GEN' 'GG' 'N64' 'NES' 'NG'
 'PC' 'PCFX' 'PS' 'PS2' 'PS3' 'PS4' 'PSP' 'PSV' 'SAT' 'SCD' 'SNES' 'TG16'
 'WS' 'Wii' 'WiiU' 'X360' 'XB' 'XOne']

unique values in "Year_of_Release":
[1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993
 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007
 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]

unique values in "Genre":
['Action' 'Action-Adventure' 'Adventure' 'Fighting' 'MMO' 'Misc' 'Music'
 'Party' 'Platform' 'Puzzle' 'Racing' 'Role-Playing' 'Shooter'
 'Simulation' 'Sports' 'Strategy' 'Visual Novel']

unique values in "Publisher":
['10TACLE Studios' '11 bit studios' '1C Company'
 '20th Century Fox Video Games' '2D Boy' '2K Sports' '3D Realms' '3DO'
 '49Games' '505 Games' '5pb' '7G//AMES' '989 Sports' '989 Studios'
 'AQ Interactive' 'ASC Games' 'ASCII Entertainment' 'ASCII Media Works'
 'ASK' 'Abylight' 'Acclaim Entertainment' 'Accolade' 'Ackkstudios'
 'Acquire' 'Active Gaming Media' 'Activision' 'Activision Blizzard'
 'Activision Value' 'Adeline Software' 'Aerosoft' 'Agatsuma Entertainment'
 'Agetec' 'Aksys Games' 'Alawar Entertainment' 'Alchemist'
 'Alternative Software' 'Altron' 'Alvion' 'American Softworks'
 'Angel Studios' 'Answer Software' 'Aqua Plus' 'Aques' 'Arc System Works'
 'Arena Entertainment' 'Aria' 'Arika' 'ArtDink' 'Aruze Corp'
 'Ascaron Entertainment' 'Ascaron Entertainment GmbH' 'Asgard'
 'Asmik Ace Entertainment' 'Asmik Corp' 'Aspyr' 'Astragon'
 'Asylum Entertainment' 'Atari' 'Athena' 'Atlus' 'Avalon Interactive'
 'Avanquest' 'Avanquest Software' 'Axela' 'BAM! Entertainment'
 'BMG Interactive Entertainment' 'BPS' 'Badland Studio'
 'Bandai Namco Entertainment' 'Bandai Namco Games' 'Banpresto' 'Benesse'
 'Berkeley' 'Bethesda Softworks' 'Big Ben Interactive' 'Big Fish Games'
 'Bigben Interactive' 'BioWare' 'Black Bean Games' 'Black Label Games'
 'Blast! Entertainment Ltd' 'Blue Byte' 'Bohemia Interactive' 'Bomb'
 'Boost On' 'Brash Entertainment' 'Broccoli' 'BushiRoad' 'CBS Electronics'
 'CCP' 'CD Projekt Red Studio' 'CDV Software Entertainment' 'CPG Products'
 'CTO SpA' 'Capcom' 'Cave' 'ChunSoft' 'City Interactive'
 'Cloud Imperium Games Corporation' 'Coconuts Japan' 'Codemasters'
 'Codemasters Online' 'CokeM Interactive' 'Coleco' 'Comfort' 'Commseed'
 'Compile' 'Compile Heart' 'Compulsion Games' 'Conspiracy Entertainment'
 'Core Design Ltd.' 'Crave Entertainment' 'Creative Core' 'Crimson Cow'
 'Crystal Dynamics' 'Crytek' 'Culture Brain' 'Culture Publishers'
 'CyberFront' 'Cygames' 'D3Publisher' 'DHM Interactive' 'DMM Games'
 'DSI Games' 'DTP Entertainment' 'Daedalic' 'Daedalic Entertainment'
 'Daito' 'Data Age' 'Data Design Interactive' 'Data East' 'Datam Polystar'
 'Deep Silver' 'Destination Software, Inc' 'Destineer' 'Detn8 Games'
 'Devolver Digital' 'DigiCube' 'Disney Interactive Studios' 'Dorart'
 'Double Damage Games' 'DreamCatcher Interactive' 'DreamWorks Interactive'
 'Dusenberry Martin Racing' 'EA Games' 'EA Sports'
 'EON Digital Entertainment' 'ESP' 'Easy Interactive' 'Ecole' 'Edia'
 'Eidos Interactive' 'Electronic Arts' 'Electronic Arts Victor' 'Elf'
 'Elite' 'Empire Interactive' 'Encore' 'Endnight Games Ltdï¿½'
 'Enix Corporation' 'Enjoy Gaming ltd.' 'Enterbrain' 'Entergram'
 'Epic Games' 'Epoch' 'Ertain' 'Essential Games' 'Evolution Games'
 'Evolved Games' 'Excalibur Publishing' 'Experience Inc.'
 'Extreme Entertainment Group' 'Falcom Corporation' 'FarSight Studios'
 'Fields' 'Flashpoint Games' 'Flight-Plan' 'Focus Home Interactive'
 'Focus Multimedia' 'Foreign Media Games' 'Fortyfive' 'Fox Interactive'
 'Frictional Games' 'From Software' 'Frontier Developments' 'FuRyu'
 'FuRyu Corporation' 'Fuji' 'FunSoft' 'Funbox Media' 'Funcom' 'Funsta'
 'Futurlab 1' 'G.Rev' 'GN Software' 'GOA' 'GSP' 'GT Interactive' 'Gaga'
 'Gainax Network Systems' 'Gakken' 'Game Arts' 'Game Factory' 'Game Life'
 'GameMill' 'GameMill Entertainment' 'GameTek' 'GameTrust' 'Gamebridge'
 'Gamecock' 'Gameloft' 'Games Workshop' 'Gathering of Developers'
 'Gearbox Software' 'General Entertainment' 'Genki' 'Genterprise'
 'Ghostlight' 'Giga' 'Giza10' 'Glams' 'Global A Entertainment'
 'Global Star' 'Gotham Games' 'Graffiti' 'Grand Prix Games'
 'Graphsim Entertainment' 'Gremlin Interactive Ltd' 'Grey Box'
 'Griffin International' 'Groove Games' 'Gun Media' 'GungHo' 'Gust'
 'HAL Laboratory' 'HMH Interactive' 'Hackberry' 'Hamster Corporation'
 'Happinet' 'Harmonix Music Systems' 'Hasbro Interactive'
 'Havas Interactive' 'Headup Games' 'Hearty Robin' 'Hect' 'Hello Games'
 'Her Interactive' 'Hip Interactive' 'Home Entertainment Suppliers'
 'Hudson Entertainment' 'Hudson Soft' 'Human Entertainment' 'HuneX'
 'IE Institute' 'ITT Family Games' 'Ice-pick Lodge' 'Iceberg Interactive'
 'Idea Factory' 'Idea Factory International' 'Ignition Entertainment'
 'Illusion Softworks' 'Imadio' 'Image Epoch' 'Imageworks' 'Imagic'
 'Imagineer' 'Imax' 'Indie Games' 'Infogrames' 'Insomniac Games'
 'Interchannel' 'Interchannel-Holon' 'Interplay' 'Interplay Productions'
 'Interworks Unlimited, Inc.' 'Inti Creates' 'Introversion Software'
 'Irem Software Engineering' 'Ivolgamus' 'JVC' 'Jack of All Games'
 'Jaleco' 'Jester Interactive' 'JoWood Productions' 'Jorudan'
 'Just Flight' 'KID' 'KSS' 'Kadokawa Games' 'Kadokawa Shoten'
 'Kaga Create' 'Kalypso Media' 'Kamui' 'Kando Games' 'Karin Entertainment'
 'Kemco' 'Kids Station' 'King Records' 'Knowledge Adventure' 'Koch Media'
 'Koei Tecmo' 'Kokopeli Digital Studios' 'Konami Digital Entertainment'
 'Kool Kizz' 'LEGO Media' 'LSP Games' 'Laguna' 'League of Geeks'
 'Legacy Interactive' 'Level 5' 'Lexicon Entertainment' 'Licensed 4U'
 'Lighthouse Interactive' 'Liquid Games' 'Little Orbit' 'Locus'
 'LucasArts' 'M2' 'MC2 Entertainment' 'MLB.com' 'MTO' 'MTV Games'
 'Mad Catz' 'Magical Company' 'Magix' 'Majesco Entertainment'
 'Mamba Games' 'Marvel Entertainment' 'Marvelous Entertainment'
 'Marvelous Games' 'Marvelous Interactive' 'Masque Publishing'
 'Mastertronic' 'Mastiff' 'Mattel Interactive' 'Max Five'
 'Maximum Family Games' 'Maximum Games' 'Maxis' 'Media Entertainment'
 'Media Factory' 'Media Rings' 'Media Works' 'MediaQuest' 'Mediascape'
 'Men-A-Vision' 'Mentor Interactive' 'Mercury Games' 'Merge Games'
 'Merscom LLC' 'Metro 3D' 'Michaelsoft' 'Micro Cabin' 'Microids'
 'Microprose' 'Microsoft Game Studios' 'Microsoft Studios'
 'Midas Interactive Entertainment' 'Midway Games' 'Milestone'
 'Milestone S.r.l' 'Milestone S.r.l.' 'Minato Station' 'Mindscape'
 'Mirai Shounen' 'Misawa' 'Mitsui' 'Mojang' 'Monte Christo Multimedia'
 'Moss' 'Mud Duck Productions' 'Mumbo Jumbo' 'Mycom' 'Myelin Media'
 'Mystique' 'NCS' 'NCSoft' 'NDA Productions' 'NEC' 'NEC Interchannel'
 'NIS America' 'Namco Bandai Games' 'Natsume' 'Navarre Corp' 'Naxat Soft'
 'Neko Entertainment' 'NetRevo' 'New' 'New World Computing' 'NewKidCo'
 'Nexon' 'Nicalis' 'Nichibutsu' 'Nighthawk Interactive'
 'Nihon Falcom Corporation' 'Nintendo' 'Nippon Amuse' 'Nippon Columbia'
 'Nippon Ichi Software' 'Nippon Telenet' 'Nitroplus' 'Nobilis'
 'Nordcurrent' 'Nordic Games' 'NovaLogic' 'Nowhere Studios' 'Number None'
 'O-Games' 'O3 Entertainment' 'Ocean' 'Office Create' 'On Demand'
 'Ongakukan' 'Origin Systems' 'Otomate' 'Outright Games'
 'Oxygen Interactive' 'P2 Games' 'PM Studios' 'PQube'
 'Pacific Century Cyber Works' 'Pack In Soft' 'Pack-In-Video' 'Palcom'
 'Panther Software' 'Paon' 'Paon Corporation' 'Paradox Development'
 'Paradox Interactive' 'Paradox Interactiveï¿½' 'Parker Bros.'
 'Perfect World Entertainment' 'Performance Designed Products'
 'Perp Games' 'Phantagram' 'Phantom EFX' 'Phenomedia' 'Phoenix Games'
 'Piacci' 'Pinnacle' 'Pioneer LDC' 'PlatinumGames' 'Play It' 'PlayV'
 'Playlogic Game Factory' 'Playmates' 'Playmore' 'Plenty' 'Pony Canyon'
 'PopCap Games' 'PopTop Software' 'Popcorn Arcade' 'Pow' 'Princess Soft'
 'Prototype' 'Psygnosis' 'Quelle' 'Quest' 'Quinrose' 'Quintet'
 'RED Entertainment' 'RTL' 'Rage Software' 'Rain Games' 'Ready at Dawn'
 'Rebellion' 'Rebellion Developments' 'Red Flagship' 'Red Orb'
 'Red Storm Entertainment' 'RedOctane' 'Reef Entertainment' 'Renegade Kid'
 'Revolution (Japan)' 'Revolution Software' 'Rising Star Games'
 'Riverhillsoft' 'Rocket Company' 'Rockstar Games' 'Rondomedia' 'Russel'
 'SCS Software' 'SCi' 'SNK' 'SNK Playmore' 'SPS' 'SSI' 'Sammy Corporation'
 'Saurus' 'Scholastic Inc.' 'Screenlife' 'Sega' 'Seta Corporation'
 'Seventh Chord' 'Shogakukan' 'Simon & Schuster Interactive' 'Sinxsoft'
 'Slightly Mad Studios' 'Slitherine Software' 'Snail Game' 'Societa'
 'Soedesco' 'Sold Out' 'Sonnet' 'Sony Computer Entertainment'
 'Sony Computer Entertainment America'
 'Sony Computer Entertainment Europe' 'Sony Interactive Entertainment'
 'Sony Music Entertainment' 'Sony Online Entertainment'
 'Sony Oznline Entertainment' 'SouthPeak Games' 'Spike' 'Spike Chunsoft'
 'Sprite' 'Square' 'Square EA' 'Square Enix' 'Square Enix ' 'SquareSoft'
 'Stainless Games' 'Starfish' 'Starpath Corp.' 'Sting' 'Storm City Games'
 'Strategy First' 'Studio Wildcard' 'Success' 'Summitsoft' 'Sunflowers'
 'Sunrise Interactive' 'Sunsoft' 'Sweets' 'Swing! Entertainment' 'Syscom'
 'System 3' 'System 3 Arcade Software' 'System Soft' 'T&E Soft' 'TDK Core'
 'TDK Mediactive' 'TGL' 'THQ' 'THQ Nordic' 'TOHO' 'TYO' 'Taito' 'Takara'
 'Takara Tomy' 'Take-Two Interactive' 'Takuyo' 'Taleworlds' 'TalonSoft'
 'Tammeka Games' 'Team Meat' 'Team17 Software' 'Techland' 'TechnoSoft'
 'Technos Japan Corporation' 'Tecmo Koei' 'Telegames' 'Telltale Games'
 'Telstar' 'Tetris Online' 'The Adventure Company' 'The Astronauts'
 'The Learning Company' 'Thekla, Inc.' 'Tigervision'
 'Time Warner Interactive' 'Titus' 'Tivola' 'Tommo' 'Tomy Corporation'
 'TopWare Interactive' 'Touchstone' 'Tradewest' 'Triangle Service'
 'Triniti Interactive' 'Trion Worlds' 'Tripwire Interactive'
 'Tru Blu Entertainment' 'Tryfirst' 'Two Tribes' 'Type-Moon' 'U.S. Gold'
 'UEP Systems' 'UFO Interactive' 'UIG Entertainment' 'Ubisoft'
 'Ubisoft Annecy' 'Universal Gamex' 'Universal Interactive' 'Unknown'
 'Valcon Games' 'ValuSoft' 'Valve' 'Valve Software' 'Vap'
 'Vatical Entertainment' 'Versus Evil' 'Vic Tokai' 'Victor Interactive'
 'Video System' 'Views' 'Vir2L Studios' 'Virgin Interactive'
 'Virtual Play Games' 'Visco' 'Vivendi Games' 'Wanadoo' 'Wander MMO'
 'Warashi' 'Wargaming.net' 'Warner Bros. Interactive Entertainment' 'Warp'
 'WayForward Technologies' 'Westwood Studios' 'White Park Bay Software'
 'Wired Productions' 'Wizard Video Games' 'Wizards of the Coast'
 'XS Games' 'Xicat Interactive' 'Xing Entertainment' 'Xplosiv'
 'Xseed Games' 'Yacht Club Games' 'Yamasa Entertainment' 'Yeti' "Yuke's"
 'Yumedia' 'Zenrin' 'Zoo Digital Publishing' 'Zoo Games' 'Zushi Games'
 'bitComposer Games' 'dramatic create' 'fonfun' 'iWin' 'id Software'
 'imageepoch Inc.' 'inXile Entertainment' 'mixi, Inc' 'responDESIGN']

Insights:
- `Platform` column could be grouped into group of console product. (i.e. Nintendo, Play Station, etc) 
    - &rarr; create new colum called `Console_Product`.
- `Publisher` column has too many unique values and some of them have a identical meaning with different named values.
    - &rarr; replace the identical value names with only one unique name.
    - &rarr; create new column called `Filtered_Publisher` to filter `Publisher` who has released more than 100 games.
- There are some zeros million number of copies in `Global_Sales`. It could be removed since doesn't hold any information for analysis.
    - &rarr; create new column called `Global_Sales (zeros)`.

In [20]:
# create group of console product
nintendo = ['3DS', 'DS', 'GB', 'GBA', 'GC', 'N64', 'NES', 'SNES', 'Wii', 'WiiU']
playstation = ['PS', 'PS2', 'PS3', 'PS4', 'PSP', 'PSV']
sega = ['DC', 'GEN', 'GG', 'SAT', 'SCD']
atari = ['2600']
_3DO = ['3DO']
NG = ['NG']
PC = ['PC']
NEC  = ['PCFX', 'TG16']
bandai = ['WS']
xbox = ['X360', 'XB', 'XOne']
vgsales['Console_Product'] = vgsales['Platform'].apply(lambda x: 'Nintendo' if x in nintendo else (
                                                                 'Playstation' if x in playstation else (
                                                                 'Sega' if x in sega else (
                                                                 'Atari' if x in atari else (
                                                                 '3DO' if x in _3DO else (
                                                                 'Neo Geo' if x in NG else (
                                                                 'PC' if x in PC else (
                                                                 'NEC' if x in NEC else (
                                                                 'Bandai' if x in bandai else (
                                                                 'Xbox')
                                                                 ))))))))
                                                      )

In [21]:
# replace the identical value names with only one unique name
vgsales['Publisher'] = vgsales['Publisher'].replace({'Activision Value':'Activision',
                                                     'Bandai Namco Games':'Bandai Namco Entertainment',
                                                     'Big Ben Interactive':'Bigben Interactive',
                                                     'Codemasters Online':'Codemasters',
                                                     'EA Sports':'Electronic Arts',
                                                     'EA Games':'Electronic Arts',
                                                     'FuRyu Corporation':'FuRyu',
                                                     'GameMill':'GameMill Entertainment',
                                                     'Hudson Entertainment':'Hudson Soft',
                                                     'Idea Factory':'Idea Factory International',
                                                     'Interchannel-Holon':'Interchannel',
                                                     'Interplay Productions':'Interplay',
                                                     'Kadokawa Shoten':'Kadokawa Games',
                                                     'Marvelous Interactive':'Marvelous Entertainment',
                                                     'Marvelous Games':'Marvelous Entertainment',
                                                     'Maximum Family Games':'Maximum Games',
                                                     'Microsoft Studios':'Microsoft Game Studios',
                                                     'Milestone S.r.l':'Milestone',
                                                     'Milestone S.r.l.':'Milestone',
                                                     'NEC Interchannel':'NEC',
                                                     'Namco Bandai Games':'Bandai Namco Entertainment',
                                                     'Paon':'Paon Corporation',
                                                     'Paradox Development':'Paradox Interactive',
                                                     'Paradox Interactiveï¿½':'Paradox Interactive',
                                                     'Rebellion':'Rebellion Developments',
                                                     'SNK':'SNK Playmore',
                                                     'Sony Computer Entertainment':'Sony Interactive Entertainment',
                                                     'Sony Computer Entertainment America':'Sony Interactive Entertainment',
                                                     'Sony Computer Entertainment Europe':'Sony Interactive Entertainment',
                                                     'Sony Online Entertainment':'Daybreak Game Company',
                                                     'Sony Oznline Entertainment':'Daybreak Game Company',
                                                     'Spike Chunsoft':'Spike',
                                                     'Square':'Square Enix',
                                                     'Square Enix ':'Square Enix',
                                                     'Square EA':'Square Enix',
                                                     'SquareSoft':'Square Enix',
                                                     'THQ':'THQ Nordic',
                                                     'Ubisoft Annecy':'Ubisoft',
                                                     'Valve Software':'Valve'})

In [22]:
# filter 'Publisher' for less than 100 games to be 'Other'
Filtered_Publisher = vgsales['Publisher'].value_counts()[vgsales['Publisher'].value_counts() >= 100].index
vgsales['Filtered_Publisher'] = vgsales['Publisher'].apply(lambda x: x if x in Filtered_Publisher else 'Other')

In [23]:
# create zeros global sales
vgsales['Global_Sales (zeros)'] = vgsales['Global_Sales'] == 0

In [24]:
# save as new .csv
vgsales.to_csv('dataset/vgsales.csv')